"""autogenerate migrations

Revision ID: 0747c74ced81
Revises: fa315ec5d9dc
Create Date: 2022-08-07 06:28:21.105625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0747c74ced81'
down_revision = 'fa315ec5d9dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_categories_name', table_name='product_categories')
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.create_index('ix_product_categories_name', 'product_categories', ['name'], unique=False)
    # ### end Alembic commands ###
