"""empty message

Revision ID: 1aad92f7a0b3
Revises: f11b7afd78f0
Create Date: 2022-06-28 15:24:45.917662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aad92f7a0b3'
down_revision = 'f11b7afd78f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'product_categories', ['product_category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'product_category_id')
    # ### end Alembic commands ###
