"""autogenerate migrations

Revision ID: 4a0a731b0f37
Revises: c9a962080886
Create Date: 2022-08-15 09:45:55.487589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a0a731b0f37'
down_revision = 'c9a962080886'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_name', table_name='products')
    op.drop_constraint('uix_name_code', 'products', type_='unique')
    op.create_unique_constraint('uix_name_code', 'products', ['product_category_id', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_name_code', 'products', type_='unique')
    op.create_unique_constraint('uix_name_code', 'products', ['name', 'code'])
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    # ### end Alembic commands ###
