"""autogenerate migrations

Revision ID: 4dee821ac345
Revises: 8200da718564
Create Date: 2022-08-15 14:21:06.541622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4dee821ac345'
down_revision = '8200da718564'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_likes', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('product_likes', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index('ix_product_likes_id', table_name='product_likes')
    op.drop_column('product_likes', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_likes', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_product_likes_id', 'product_likes', ['id'], unique=False)
    op.alter_column('product_likes', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('product_likes', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
