"""autogenerate migrations

Revision ID: 4e1f5b37ba27
Revises: 6f612d38f7a2
Create Date: 2022-09-04 06:16:27.855634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e1f5b37ba27'
down_revision = '6f612d38f7a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
