"""init db autogenerate migrations

Revision ID: 637641e6b429
Revises: fd37cdc63b54
Create Date: 2022-07-05 12:39:06.088277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '637641e6b429'
down_revision = 'fd37cdc63b54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_Deleted')
    op.add_column('posts', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_deleted')
    op.add_column('posts', sa.Column('is_Deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
