"""autogenerate migrations

Revision ID: 6f612d38f7a2
Revises: 4dee821ac345
Create Date: 2022-09-04 05:58:46.966117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f612d38f7a2'
down_revision = '4a5268577464'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('uid', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('picture', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('type', sa.Enum('admin', 'basic', name='usertype'), nullable=False))
    op.create_unique_constraint('ix_users_uid', 'users', ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ix_users_uid', 'users', type_='unique')
    op.drop_column('users', 'type')
    op.drop_column('users', 'picture')
    op.drop_column('users', 'uid')
    # ### end Alembic commands ###
