"""init db autogenerate migrations

Revision ID: 7224da3668e1
Revises: 637641e6b429
Create Date: 2022-07-11 13:06:49.132995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7224da3668e1'
down_revision = '637641e6b429'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_categories', sa.Column('owner_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_categories', 'owner_id')
    # ### end Alembic commands ###
