"""init db autogenerate migrations

Revision ID: 75033dbdbb96
Revises: 7224da3668e1
Create Date: 2022-07-11 14:05:19.698086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75033dbdbb96'
down_revision = '7224da3668e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_categories', sa.Column('code', sa.String(length=100), nullable=True))
    op.create_unique_constraint('uix_name_code', 'product_categories', ['name', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_name_code', 'product_categories', type_='unique')
    op.drop_column('product_categories', 'code')
    # ### end Alembic commands ###
