"""autogenerate migrations

Revision ID: bf95568cafff
Revises: 4e1f5b37ba27
Create Date: 2022-09-06 15:13:19.597572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf95568cafff'
down_revision = '4e1f5b37ba27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review_likes', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('review_likes', 'review_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index('ix_review_likes_id', table_name='review_likes')
    op.drop_column('review_likes', 'id')
    op.drop_index('ix_users_uid', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_uid', 'users', ['uid'], unique=False)
    op.add_column('review_likes', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_review_likes_id', 'review_likes', ['id'], unique=False)
    op.alter_column('review_likes', 'review_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('review_likes', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
