"""autogenerate migrations

Revision ID: c9a962080886
Revises: f6c55139e1b4
Create Date: 2022-08-10 00:36:40.696640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a962080886'
down_revision = 'f6c55139e1b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_code', table_name='products')
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=False)
    op.drop_index('ix_products_name', table_name='products')
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_unique_constraint('uix_name_code', 'products', ['name', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_name_code', 'products', type_='unique')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.create_index('ix_products_name', 'products', ['name'], unique=False)
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.create_index('ix_products_code', 'products', ['code'], unique=False)
    # ### end Alembic commands ###
