"""autogenerate migrations

Revision ID: f6c55139e1b4
Revises: 0747c74ced81
Create Date: 2022-08-07 09:30:22.169296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c55139e1b4'
down_revision = '0747c74ced81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('code', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_products_code'), 'products', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_code'), table_name='products')
    op.drop_column('products', 'code')
    # ### end Alembic commands ###
