"""autogenerate migrations

Revision ID: fa315ec5d9dc
Revises: 85abf1eb5fb1
Create Date: 2022-08-02 14:28:26.684238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa315ec5d9dc'
down_revision = '85abf1eb5fb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('status', sa.Enum('active', 'soldOut', 'delete', name='statustype'), server_default='active', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'status')
    # ### end Alembic commands ###
