"""init db autogenerate migrations

Revision ID: fd37cdc63b54
Revises: 1aad92f7a0b3
Create Date: 2022-07-05 12:33:54.423876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd37cdc63b54'
down_revision = '1aad92f7a0b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(length=200), nullable=False))
    op.add_column('posts', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('posts', sa.Column('is_Deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_Deleted')
    op.drop_column('posts', 'updated_at')
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
